### ISSUE TITLE
Client Timeout Error

### ISSUE THREAD

**Issue by MiguelCosta1993** [OTRF/ATTACK-Python-Client#87]
Similar to this issue [https://github.com/OTRF/ATTACK-Python-Client/issues/83](url) I'm having issues accessing the TAXII server.

I have the version 0.4.2 of attackcti (isn't the latest but I didn't think it would make a difference with the changes on the 0.4.4)

Leaving the context below:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x711796669390>, 'Connection to cti-taxii.mitre.org timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cti-taxii.mitre.org', port=443): Max retries exceeded with url: /stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x711796669390>, 'Connection to cti-taxii.mitre.org timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/misp2vectr/MISP2VECTRAgentTeste.py", line 808, in <module>
    runScript(args)
  File "/home/misp2vectr/MISP2VECTRAgentTeste.py", line 734, in runScript
    assessments = threat_landscape_to_assessments(threats, misp, args.priority, datefrom, org_name, args.name, args.testcase_limit)
  File "/home/misp2vectr/MISP2VECTRAgentTeste.py", line 512, in threat_landscape_to_assessments
    new_campaigns = misp_events_to_campaign(mal_events, TT_covered, org_name, testcase_limit)
  File "/home/misp2vectr/MISP2VECTRAgentTeste.py", line 305, in misp_events_to_campaign
    atck_cli = attack_client()
  File "/usr/local/lib/python3.10/dist-packages/attackcti/attack_api.py", line 98, in __init__
    self.TC_ENTERPRISE_SOURCE = TAXIICollectionSource(ENTERPRISE_COLLECTION)
  File "/usr/local/lib/python3.10/dist-packages/stix2/datastore/taxii.py", line 163, in __init__
    if collection.can_read:
  File "/usr/local/lib/python3.10/dist-packages/taxii2client/v20/__init__.py", line 316, in can_read
    self._ensure_loaded()
  File "/usr/local/lib/python3.10/dist-packages/taxii2client/v20/__init__.py", line 388, in _ensure_loaded
    self.refresh()
  File "/usr/local/lib/python3.10/dist-packages/taxii2client/v20/__init__.py", line 402, in refresh
    response = self.__raw = self._conn.get(
  File "/usr/local/lib/python3.10/dist-packages/taxii2client/common.py", line 297, in get
    resp = self.session.get(url, headers=merged_headers, params=params)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='cti-taxii.mitre.org', port=443): Max retries exceeded with url: /stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x711796669390>, 'Connection to cti-taxii.mitre.org timed out. (connect timeout=None)'))

**Comment by Cyb3rWard0g** [comment]
Hey @MiguelCosta1993 !

I would recommend initializing the client with the new version which downloads stix data from the latest version / release from https://github.com/mitre-attack/attack-stix-data

```python
from attackcti import MitreAttackClient

# Downloads latest STIX 2.1 (enterprise+mobile+ics) to .attackcti/stix-2.1 (reuses files if present)
lift = MitreAttackClient.from_attack_stix_data()
```

an example: https://github.com/OTRF/ATTACK-Python-Client/blob/master/docs/playground/1-Collect_All_Functions.ipynb

The new TAXII Server has limitations

https://github.com/mitre-attack/attack-workbench-taxii-server/blob/main/docs/USAGE.md

# TAXII 2.1 API User Guide

> [!WARNING]
> The TAXII server hosted at `https://attack-taxii.mitre.org` is rate limited to only accept 10 requests per 10 minute period per source IP address.
> If you find yourself needing to query ATT&CK's content more frequently, please consider downloading the STIX/JSON bundles
> and parsing them directly. More information on this process can be found [here](https://github.com/mitre-attack/attack-stix-data/blob/master/USAGE.md)
